child(X, queen_elizabeth).
mother(X, prince_charles).
grandparent(X, prince_william).
grandchild(X, prince_philip).
wife(kate_middleton, prince_william).
aunt(X, prince_harry).
parent(X, prince_george).
sibling(X, princess_beatrice).
brother(peter_phillips, zara_phillips).
niece(X, prince_edward).
grandfather(prince_philip, mia_grace_tindall).
granddaughter(X, prince_charles).
nephew(X, prince_andrew).
grandfather(X, peter_phillips).
son(james_viscount_severn, sophie_rhys_jones).
husband(X, princess_anne).
uncle(X, camilla_parker_bowles).
daughter(X, peter_phillips).
grandson(X, queen_elizabeth).
sister(savannah_phillips, isla_phillips).
grandmother(X, lady_louise_mountbatten_windsor).